# Generated by Django 3.2.1 on 2021-05-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product_desc', models.CharField(max_length=255)),
                ('current_price', models.FloatField()),
                ('real_price', models.FloatField()),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images')),
            ],
        ),
    ]
