# Generated by Django 3.2.1 on 2021-05-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
